name: recharge_by_scan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.0
  intl: ^0.19.0
  floor: ^1.5.0
  retrofit: ^4.4.1
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  background_sms: ^0.0.4
  sim_card_info: ^1.0.2
  telephony: ^0.2.0
  #sms_receiver: ^0.4.2
  readsms: ^0.2.0+4
  google_mlkit_text_recognition: ^0.13.1
  camera: ^0.11.0+2
  go_router: ^14.3.0
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.12
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imgs/